#!/bin/bash

#######################################################
##  aaronbeveridge.com
#######################################################

#######################################################
## My personal website is built with Pandoc using
## markdown. Site navigation is created with Pandoc's
## include-before-body function by inserting nav.html
## into every page's HTML when it is built by Pandoc.
####################################################### 

#Home page
pandoc ./markdown/home.md \
--css style.css \
--template ./templates/main.html \
--output index.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="welcome"

#CV page
pandoc ./markdown/cv.md \
--css style.css \
--template ./templates/main.html \
--output cv.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="cv" \
--toc

#Projects page
pandoc ./markdown/projects.md \
--css style.css \
--template ./templates/main.html \
--output projects.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="projects" 

#Teaching page
pandoc ./markdown/teaching.md \
--css style.css \
--template ./templates/main.html \
--output teaching.html \
--smart \
--include-before-body ./templates/nav.html \
--title-prefix="teaching" 
#--include-after-body ./templates/footer.html \

#git add --all
#git commit -m "updates"
#git push
