#!/bin/bash

#######################################################
##  aaronbeveridge.com
#######################################################

#######################################################
## My personal website is built with Pandoc using
## markdown. Site navigation is created with Pandoc's
## include-before-body function by inserting nav.html
## into every page's HTML when it is built by Pandoc.
####################################################### 

#Home page
pandoc ./markdown/home.md \
--css pandoc.css \
--template ./templates/template.html \
--output index.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="Welcome"

#CV page
pandoc ./markdown/cv.md \
--css pandoc.css \
--template ./templates/template.html \
--output cv.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="CV"

#Projects page
pandoc ./markdown/projects.md \
--css pandoc.css \
--template ./templates/template.html \
--output projects.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="Projects" 

#git add --all
#git commit -m "updates"
#git push
