#!/bin/bash

#######################################################
##  massmine.org build script
#######################################################

#home
pandoc ./src/md/home.md \
--template ./src/frames/main.html \
--output index.html

#docs main
pandoc ./src/md/docs.md \
--template ./src/frames/docs-nav.html \
--output ./docs/index.html

#install
pandoc ./src/md/install.md \
--template ./src/frames/docs-nav.html \
--output ./docs/install.html \
--toc

#authentication
pandoc ./src/md/authorization.md \
--template ./src/frames/docs-nav.html \
--output ./docs/authorization.html \
--toc

#usage & config
pandoc ./src/md/config.md \
--template ./src/frames/docs-nav.html \
--output ./docs/config.html \
--toc

#google trends
pandoc ./src/md/google.md \
--template ./src/frames/docs-nav.html \
--output ./docs/google.html \
--toc

#tumblr
pandoc ./src/md/google.md \
--template ./src/frames/docs-nav.html \
--output ./docs/google.html \
--toc

#twitter
pandoc ./src/md/twitter.md \
--template ./src/frames/docs-nav.html \
--output ./docs/twitter.html \
--toc

#wikipedia
pandoc ./src/md/wikipedia.md \
--template ./src/frames/docs-nav.html \
--output ./docs/wikipedia.html \
--toc

#web scraping
pandoc ./src/md/web.md \
--template ./src/frames/docs-nav.html \
--output ./docs/web.html \
--toc

#twitter analysis
pandoc ./src/md/twitter-analysis.md \
--template ./src/frames/docs-nav.html \
--output ./docs/twitter-analysis.html \
--toc
